site_name: PanZoom Plugin for MkDocs
site_dir: public
repo_name: PLAYG0N/mkdocs-panzoom
repo_url: https://github.com/PLAYG0N/mkdocs-panzoom
site_url: https://playg0n.github.io/mkdocs-panzoom/

theme:
  name: material
  icon:
    logo: material/magnify-scan
  palette:
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

  features:
    - content.code.copy
    - navigation.indexes
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
# Extensions
markdown_extensions:
  - footnotes
  - attr_list
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.tasklist
  - admonition
  - toc:
      permalink: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

plugins:
  - search
  - panzoom:
      images: true
      mermaid: true
      full_screen: true
      always_show_hint: false
      exclude:
        - Mermaid/excluded.md
