site_name: PanZoom Plugin for MkDocs
site_dir: public
repo_name: PLAYG0N/mkdocs-panzoom
repo_url: https://github.com/PLAYG0N/mkdocs-panzoom

theme:
  name: material
  palette:
    scheme: slate
  features:
    - content.code.copy
    - navigation.indexes
    - navigation.tabs
    - navigation.top
# Extensions
markdown_extensions:
  - footnotes
  - attr_list
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.magiclink
  - pymdownx.tasklist
  - pymdownx.emoji
  - admonition
  - toc:
      permalink: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

plugins:
  - search
  - roamlinks
  - panzoom:
      exclude:
        - Mermaid/excluded.md
